name: Pipeline Frontend

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Verificar Linting y Formateo
      run: npm run lint

    - name: Ejecutar Pruebas Unitarias (Jest)
      run: npm run test

    - name: Compilar Proyecto (TypeScript a JS)
      run: npm run build
